"""Added book_added to Book

Revision ID: 2494496da672
Revises: d775871e0251
Create Date: 2021-02-03 21:31:55.924236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2494496da672'
down_revision = 'd775871e0251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_added', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_added')
    # ### end Alembic commands ###
