"""Changed year_founded type

Revision ID: 9881d8e64b4d
Revises: af66054c0640
Create Date: 2021-02-03 01:19:11.272331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9881d8e64b4d'
down_revision = 'af66054c0640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'how_much_read',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True ,
               postgresql_using='how_much_read::VARCHAR'
               )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'how_much_read',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
