"""Changed varchar to integer

Revision ID: d775871e0251
Revises: 9881d8e64b4d
Create Date: 2021-02-03 01:26:07.936864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd775871e0251'
down_revision = '9881d8e64b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'how_much_read',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True , 
               postgresql_using='how_much_read::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'how_much_read',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
